// <auto-generated />
namespace SapatariaBiblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V3));
        
        string IMigrationMetadata.Id
        {
            get { return "201808120014570_V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
